 AWSTemplateFormatVersion: 2010-09-09 
 Mappings: 
  AMIIDMap: 
    us-east-1: 
       MyAMI1: ami-0ff8a91507f77f867 
       MyAMI2: ami-0a584ac55a7631c0c 
     us-west-1: 
       MyAMI1: ami-0bdb828fd58c52235 
       MyAMI2: ami-066ee5fd4a9ef77f1 
     eu-west-1: 
       MyAMI1: ami-047bb4163c506cd98 
       MyAMI2: ami-0a7c483d527806435 
     ap-northeast-1: 
       MyAMI1: ami-06cd52961ce9f0d85 
       MyAMI2: ami-053cdd503598e4a9d 
     ap-southeast-1: 
       MyAMI1: ami-08569b978cc4dfa10 
       MyAMI2: ami-0be9df32ae9f92309 
 Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance" 
     Properties: 
      ImageId: !FindInMap [AMIIDMap, !Ref "AWS::Region", MyAMI1] 
       InstanceType: t2.micro
